config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#index"

  devise_for :users
  devise_scope :user do
    get "/logout", :to => "devise/sessions#destroy"
  end

  get '/secure_page' => 'welcome#secure_page'

  get '/cache' => 'cache#index'

  # Sample routes
  # Plural resource
  resources :photos

  # Singular resource
  resource :geocoder

  # Namespace
  namespace :admin do
    resources :articles, :comments
  end

  # Nested
  resources :magazines do
    resources :ads
  end

  # Dynamic non-RESTful
  # get ':controller(/:action(/:id))', controller: /admin\/[^\/]+/
  # get ':controller/:action/:id/with_user/:user_id'

  # With defaults
  get 'photos/:id', to: 'photos#show', defaults: { format: 'jpg' }

  # With constraints
  get 'photos_with_constraints/:id/:user_id', to: 'photos#show', constraints: { id: /[A-Z]\d{5}/, user_id: /[a-z]\d{4}/ }

  # Route globbing
  get 'books/*section/:title', to: 'books#show'

  # Redirect
  get '/stories', to: redirect('/articles')
  get '/stories/:name', to: redirect { |path_params, req| "/articles/#{path_params[:name].pluralize}" }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)

    can :action_a, User
    cannot :action_b, User
    can :action_c, User
    can :action_d, User do |user|
      user.email.present?
    end

    if user.email.present?
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_attached_file :avatar, :path => 'secret/:attachment/:id/location/:filename',
  #                   :styles => { :medium => "300x300>", :thumb => "100x100>" },
  #                   :default_url => "/images/:attachment/:style/missing.png"
  #
  # has_attached_file :headshot, :path => ':class/:attachment/:id/location/:filename',
  #                   :styles => { :large => "600x600>" },
  #                   :default_url => "/images/:attachment/:style/missing.png"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  abstract!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController

  def index
    Rails.cache.write('tuttle-demo.key1', 'Monday')
    Rails.cache.read('tuttle-demo.key1')
    Rails.cache.read('tuttle-demo.key2')
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, :only => [:secure_page]

  def index
  end

  def secure_page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def application_helper_example
    'This is from the ApplicationHelper application_helper_example'
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def welcome_helper_example
    'This is from the WelcomeHelper welcome_helper_example'
  end

end

app/views/cache/index.html.haml
.container
  .row{style: 'margin-top: 70px;'}
    .col-md-8
      %h2 Rails Caching Demo
      %p
        This page will generate cache interactions that will appear in the
        = link_to 'Tuttle Cache Inspector', tuttle.rails_cache_path, :class=>['btn','btn-primary'], :role=>'button'

    .col-md-4
      #caching.panel.panel-default
        .panel-heading
          %h3.panel-title Cached Output Examples
        .panel-body
          %p Current time #{Time.now}
          - cache_if(!!params[:test], params[:test]) do
            %p Test with test_if(#{!!params[:test]}, #{params[:test]})
          - cache('cache_test') do
            %p Test
          - cache(['cache_test','array']) do
            %p Test with array of keys
          - cache_if(!!params[:test], params[:test]) do
            %p Test with test_if(#{!!params[:test]}, #{params[:test]})
          - cache('cache_test_without_digest', skip_digest: true) do
            %p Test without digest
          - cache(['cache_test','array']) do
            %p Test with array of keys
          - if true # disabled waiting for rails 5 patch
            %p= Rails.cache.fetch('cache_test_with_expires', {:expires_in => 1.minute}) { "Test with 1 minute expiration at #{Time.now}" }
            %p= Rails.cache.fetch('cache_test_with_force', {:force => true}) { "Test with :force => true" }
            %p= Rails.cache.fetch('cache_test_with_compress', {:compress => true}) { "Test with :compress => true" }
            %p= Rails.cache.fetch('cache_test_with_raw', {:raw => true}) { "Test with :raw => true" }
          - else # restore these helper calls when patch is accepted
            - cache('cache_test_with_expires', {:expires_in => 1.minute}) do
              %p Test with 1 minute expiration at #{Time.now}
            - cache('cache_test_with_force', force: true) do
              %p Test with :force => true
            - cache('cache_test_with_compress', compress: true) do
              %p Test with :compress => true
            - cache('cache_test_with_raw', raw: true) do
              %p Test with :raw => true
          - # no example of :race_condition_ttl option

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tuttle Demo</title>
  <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-Xqcy5ttufkC3rBa8EdiAyA1VgOGrmel2Y+wxm4K3kI3fcjTWlDWrlnxyD6hOi3PF" crossorigin="anonymous">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="icon" href="<%= image_path 'favicon.ico' %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('Tuttle Demo', root_path, :class => 'navbar-brand') %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right hide">
        <% if user_signed_in? %>
          <li style="padding: 15px 0;">You are signed in as <%= current_user.email %></li>
          <li><%= link_to 'Sign Out', logout_path %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        <li><%= link_to 'Secure Page', secure_page_path %></li>
      </ul>
    </div>
  </div>
</nav>

<%= yield -%>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/welcome/index.html.haml
.jumbotron
  .container
    %h1 Welcome

    %p
      This is the Tuttle Demo application which demonstrates the
      capabilities of Tuttle.
    %p
      This application is a Rails 5.x minimal application with a few
      gems (Devise, CanCan, etc) installed to show off
      their inspectors.

    %p= link_to 'Tuttle Dashboard »', tuttle.root_path, :class=>['btn','btn-primary','btn-lg'], :role=>'button'

.container
  .row
    .col-md-6
      .h2 Rails
      %p
        This basic Rails application consists of a few controllers and a few models hitting a PostgreSQL database.
      %p
        Tuttle can help inspect Rails applications with knowledge of configuration best practices.
        You can use Tuttle to inspect Models, Controllers, Helpers, Engines, Generators, and more.
      %p= link_to 'Tuttle Rails', tuttle.rails_path, :class=>['btn','btn-primary'], :role=>'button'
    .col-md-6
      .h2 Ruby
      %p
        Tuttle's Ruby inspector support allows you see how Ruby itself has been configured.
        You can get details into Garbage Collection, tuning parameters, and environment variables.
      %p
        Tuttle will also report on which files have been loaded by Kernel.
      %p
        = link_to 'Tuttle Ruby', tuttle.ruby_path, :class=>['btn','btn-primary'], :role=>'button'

  .row

    .col-md-6
      %h2 ActiveSupport
      %p
        Tuttle can help inspect how ActiveSupport is configured, including Inflectors and Timezones.
      %p
        The inspector can also report on which dependencies have been loaded, autoloaded, and eager-loaded.
      %p
        = link_to 'Tuttle ActiveSupport', tuttle.active_support_path, :class=>['btn','btn-primary'], :role=>'button'

    .col-md-6
      %h2 Gems
      %p
        This application includes several open source Gems which Tuttle can detect.
      %ul
        %li Devise authentication with self registration
        %li CanCan authorization with simple rules
      %p
        = link_to 'Tuttle Devise', tuttle.devise_path, :class=>['btn','btn-primary'], :role=>'button'
        = link_to 'Tuttle CanCan', tuttle.cancancan_path, :class=>['btn','btn-primary'], :role=>'button'

  .row

    .col-md-6
      .h2 Caching
      %p
        Tuttle's Ruby inspector provides insights into the Cache configuration of
        your application.
      %p
        = link_to 'Tuttle Cache', tuttle.rails_cache_path, :class=>['btn','btn-primary'], :role=>'button'
        = link_to 'Tuttle Demo Cache Exerciser', cache_path, :class=>['btn','btn-info'], :role=>'button'

    .col-md-6
      %h2 Profiling
      %p
        Tuttle includes an on-demand request profiling middleware to allow you to
        inspect memory or CPU usage of a request.
      %p
        Just add <code>?tuttle-profiler=memory</code> or
        <code>?tuttle-profiler=cpu</code> to any URL to invoke the profiler.

      %p
        = link_to 'Memory Profiler', tuttle.root_path('tuttle-profiler':'memory'), :class=>['btn','btn-primary'], :role=>'button'
        = link_to 'CPU Profiler', tuttle.root_path('tuttle-profiler':'cpu'), :class=>['btn','btn-primary'], :role=>'button'

  %hr
  %footer
    %p
      = link_to '&copy; 2017 Dave Gynn'.html_safe, 'https://github.com/dgynn/tuttle'

app/views/welcome/secure_page.html.haml
%h2 This is a secure page

And you are #{current_user.email}